[phases.setup]
nixPkgs = ["python312", "unzip"]

[phases.install]
cmds = ["pip install -r requirements.txt", "reflex init"]

[start]
cmd = "reflex run --env prod --backend-host 0.0.0.0 --backend-port $PORT"
